
events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name _;

        location /media/ {
            alias /var/www/media/hls/;

            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
            add_header Access-Control-Allow-Headers "*" always;

            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }

            if ($request_method = OPTIONS) {
                return 204;
            }
        }
    }
}
